Added docker capabilities flag and attributes
squarescale/squarescale-cli pull request #128
Opened 2022-12-30 13:18 UTC by Isilud

2022-12-30 13:47 UTC, obourdon requested changes

2022-12-30 13:47 UTC, obourdon commented on command/container-show.go
> +			tbl += fmt.Sprintf("Enabled capabilities: \t%s \n", strings.Join(co.DockerCapabilities, ", "))
no space just comma (even if it is more readable, this could avoid a lot of parsing/potential issues

2022-12-30 13:47 UTC, obourdon commented on squarescale/batches.go
> +	Name           		 string      	`json:"name"`
formatting seems weird (run `go fmt` to make sure)

2022-12-30 13:47 UTC, obourdon commented on squarescale/batches.go
> +		"name":            					batchOrderContent.BatchCommon.Name,
weird formatting again

2022-12-30 13:47 UTC, obourdon commented on squarescale/services.go
> +	ID               	 int               `json:"container_id"`
formatting again

2022-12-30 16:40 UTC, Isilud commented
noDockerCapabilitiesFlag still unused. Need to define payload["docker_capabilities"] for all use case.

2023-01-02 08:36 UTC, Isilud commented
If noDockerCapabilitiesFlag is set to true then the payload will contain the attribute docker_capabilities = ['NONE'].
If not, then the value will be the one specified by the user or an empty array.
In the case of an update of an existing service and no flag set, no attribute docker_capabilities will be sent with the payload.

2023-01-02 08:47 UTC, SwannCroiset commented
#127

2023-01-02 09:41 UTC, obourdon approved these changes
LGTM

2023-01-05 10:44 UTC, obourdon approved these changes

2023-01-05 10:52 UTC, ika108 approved these changes

2023-01-05 13:33 UTC, merged