add docker-devices mapping
squarescale/squarescale-cli pull request #139
Opened 2023-03-29 09:30 UTC by Isilud

2023-03-31 09:28 UTC, ika108 submitted a review, later dismissed

2023-04-12 13:07 UTC, obourdon requested changes

2023-04-12 13:07 UTC, obourdon commented on command/flags.go
> +	return f.String("docker-devices", "", "The list of device mapping if any, separated with a comma. format: src:opt:dst")
This is incoherent with [https://github.com/squarescale/front/commit/25aff16727166a359d813a70703ab0d3d746c67e](https://github.com/squarescale/front/commit/25aff16727166a359d813a70703ab0d3d746c67e)

must be something like 
```
"The list of device mappings if any, separated with commas. format: src:dst[:opt][,src:dst[:opt]]*"
```

2023-04-13 07:01 UTC, obourdon approved these changes

2023-04-13 09:09 UTC, SwannCroiset commented on .github/workflows/test.yml
> +          if [ -f Gopkg.toml ]; then
Gopkg.toml ?

2023-04-13 09:10 UTC, SwannCroiset reviewed
LGTM except  golang/dep

2023-04-13 09:54 UTC, merged